/*
 * MemM_LCfg.c
 *
 * Created: 6/9/2021
 *  Author: Ahmed Nabil
 */ 


#include "MemM.h"

MemM_BlockConfig_t MemM_BlocksConfig[MEMM_USED_BLOCKS_NUM] = 
{
	{MEMIF_EEPROM_256K_ID, MEMM_VALID_DEVICE_FLAG_LOC, MEMM_VALID_DEVICE_FLAG_SIZE},
	{MEMIF_EEPROM_256K_ID, MEMM_CONNECTED_DEVICE_NAME_LOC, MEMM_CONNECTED_DEVICE_NAME_SIZE},
	{MEMIF_EEPROM_256K_ID, MEMM_CONNECTED_DEVICE_MAC_LOC, MEMM_CONNECTED_DEVICE_MAC_SIZE},
	{MEMIF_EEPROM_256K_ID, MEMM_CONNECTED_DEVICE_DATA_PACK_LOC, MEMM_CONNECTED_DEVICE_DATA_PACK_SIZE}
}