 /******************************************************************************
 *
 * Module: PORT
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for Port Module.
 *
 * Author: Ahmed Nabil
 ******************************************************************************/


#include "Port.h"


/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between PORT_PBcfg.c and PORT.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the AR version of Port.h"
#endif

/* Software Version checking between PORT_PBcfg.c and PORT.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the SW version of Port.h"
#endif

/* PB structure used with Port_Init API */
const Port_ConfigType Port_PinsConfigurations = 
{	
	{
	/* Port A Pin Configurations */
	/*  Pin ID     Pin Direction   Direction Changeable?     Initial Level  Port Pin Mode      Mode Changeable?           Digital Enable?         Pin Drive Current      OpenDrain Pin?           SlewRate Pin?         AMSEL Pin? */
//	{PORT_A_PIN_0, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
//	{PORT_A_PIN_1, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
    {PORT_A_PIN_2, PORT_PIN_OUT, PORT_PIN_DIRECTION_CHANGEABLE, PULL_NONE, PORT_PIN_MODE_SPI0_PORTA, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_A_PIN_3, PORT_PIN_OUT, PORT_PIN_DIRECTION_CHANGEABLE, STD_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_A_PIN_4, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_NONE, PORT_PIN_MODE_SPI0_PORTA, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_A_PIN_5, PORT_PIN_OUT, PORT_PIN_DIRECTION_CHANGEABLE, PULL_NONE, PORT_PIN_MODE_SPI0_PORTA, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_A_PIN_6, PORT_PIN_OUT, PORT_PIN_DIRECTION_CHANGEABLE, STD_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_A_PIN_7, PORT_PIN_OUT, PORT_PIN_DIRECTION_CHANGEABLE, STD_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	/* Port B Pin Configurations */
	/*  Pin ID     Pin Direction   Direction Changeable?     Initial Level  Port Pin Mode      Mode Changeable?           Digital Enable?         Pin Drive Current      OpenDrain Pin?           SlewRate Pin?         AMSEL Pin? */
	{PORT_B_PIN_0, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_B_PIN_1, PORT_PIN_OUT, PORT_PIN_DIRECTION_CHANGEABLE, STD_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_B_PIN_2, PORT_PIN_OUT, PORT_PIN_DIRECTION_CHANGEABLE, STD_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_B_PIN_3, PORT_PIN_OUT, PORT_PIN_DIRECTION_CHANGEABLE, STD_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_B_PIN_4, PORT_PIN_OUT, PORT_PIN_DIRECTION_CHANGEABLE, PULL_NONE, PORT_PIN_MODE_SPI2_PORTB, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_B_PIN_5, PORT_PIN_OUT, PORT_PIN_DIRECTION_CHANGEABLE, STD_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_B_PIN_6, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_NONE, PORT_PIN_MODE_SPI2_PORTB, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_B_PIN_7, PORT_PIN_OUT, PORT_PIN_DIRECTION_CHANGEABLE, PULL_NONE, PORT_PIN_MODE_SPI2_PORTB, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	/* Port C Pin Configurations */
	/*  Pin ID     Pin Direction   Direction Changeable?     Initial Level  Port Pin Mode      Mode Changeable?           Digital Enable?         Pin Drive Current      OpenDrain Pin?           SlewRate Pin?         AMSEL Pin? */
	//{PORT_C_PIN_0, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	//{PORT_C_PIN_1, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	//{PORT_C_PIN_2, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	//{PORT_C_PIN_3, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_C_PIN_4, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_C_PIN_5, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_C_PIN_6, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_C_PIN_7, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	/* Port D Pin Configurations */
	/*  Pin ID     Pin Direction   Direction Changeable?     Initial Level  Port Pin Mode      Mode Changeable?           Digital Enable?         Pin Drive Current      OpenDrain Pin?           SlewRate Pin?         AMSEL Pin? */
	{PORT_D_PIN_0, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_D_PIN_1, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_D_PIN_2, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_D_PIN_3, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_D_PIN_4, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_D_PIN_5, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_D_PIN_6, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_D_PIN_7, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	/* Port E Pin Configurations */
	/*  Pin ID     Pin Direction   Direction Changeable?     Initial Level  Port Pin Mode      Mode Changeable?           Digital Enable?         Pin Drive Current      OpenDrain Pin?           SlewRate Pin?         AMSEL Pin? */
	{PORT_E_PIN_0, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_E_PIN_1, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_E_PIN_2, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_E_PIN_3, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_E_PIN_4, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_E_PIN_5, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_E_PIN_6, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_E_PIN_7, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	/* Port F Pin Configurations */
	/*  Pin ID     Pin Direction   Direction Changeable?     Initial Level  Port Pin Mode      Mode Changeable?           Digital Enable?         Pin Drive Current      OpenDrain Pin?           SlewRate Pin?         AMSEL Pin? */
	{PORT_F_PIN_0, PORT_PIN_IN, PORT_PIN_DIRECTION_UNCHANGEABLE, PULL_UP, PORT_PIN_MODE_DIO, PORT_PIN_MODE_UNCHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_F_PIN_1, PORT_PIN_OUT, PORT_PIN_DIRECTION_UNCHANGEABLE, STD_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_UNCHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_F_PIN_2, PORT_PIN_OUT, PORT_PIN_DIRECTION_UNCHANGEABLE, STD_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_UNCHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_F_PIN_3, PORT_PIN_OUT, PORT_PIN_DIRECTION_UNCHANGEABLE, STD_LOW, PORT_PIN_MODE_DIO, PORT_PIN_MODE_UNCHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_F_PIN_4, PORT_PIN_IN, PORT_PIN_DIRECTION_UNCHANGEABLE, PULL_UP, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_F_PIN_5, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_F_PIN_6, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	{PORT_F_PIN_7, PORT_PIN_IN, PORT_PIN_DIRECTION_CHANGEABLE, PULL_DOWN, PORT_PIN_MODE_DIO, PORT_PIN_MODE_CHANGEABLE, PORT_PIN_DIGITAL_ENABLE, PORT_PIN_CURRENT_2mA, PORT_OPENDRAIN_DISABLE, PORT_SLEWRATE_DISABLE, PORT_AMSEL_DISABLE},
	}
};
